cabinetoffice/gap-find-admin-backend

src/main/java/gov/cabinetoffice/gap/adminbackend/dtos/ValidateSessionsRolesRequestBodyDTO.java
src/main/java/gov/cabinetoffice/gap/adminbackend/services/UserService.java
src/test/java/gov/cabinetoffice/gap/adminbackend/services/UserServiceTest.java

fixes a bug where email addresses containing a + can't log in. (when the `verify-user-roles-in-middleware` flag is true)
The right side of the + was removed from the query string, fix is to use a post request instead

'+' bugfix - refactor service to send a post request

---

src/main/resources/db/migration/V1_66__alter_scheduler_database_view.sql
src/main/resources/db/migration/V1_68__alter_scheduler_database_view.sql

Discovered the database stored our opening/closing dates as `timestamp without time zone` whereas JPA stores as an instant, set to the `Europe/London` zone.
This PR changes the columns to support the timezone:
And additionally modifies the view to look backwards incase it missed any ads that needed publishing/unpublishing

GAP-2148: grant advert not publishing on selected date

---

src/main/java/gov/cabinetoffice/gap/adminbackend/services/SubmissionsService.java

The lambda is invoked before the transaction that inserts all the exports finishes for sufficiently large grants

GAP-2230: First export fails due to transactional

---

src/main/resources/db/migration/V1_73__create_spotlight_submission_table.sql

https://technologyprogramme.atlassian.net/jira/software/projects/TMI2/boards/331?selectedIssue=TMI2-392

TMI2-392:  Migration update for spotlight submission table

---

src/main/java/gov/cabinetoffice/gap/adminbackend/controllers/UserController.java
src/main/java/gov/cabinetoffice/gap/adminbackend/dtos/CheckNewAdminEmailDto.java

GAP-1784: User can't assign grant to current owner

---

src/main/java/gov/cabinetoffice/gap/adminbackend/services/GrantMandatoryQuestionService.java
src/test/java/gov/cabinetoffice/gap/adminbackend/services/GrantMandatoryQuestionServiceTest.java

Inside `buildSingleSpotlightRow` method, non-mandatory value can be null and this was throwing a nullpointer exception when creating `List.of(null)` . I added a check so that if it's null, it will pass an empty string instead of null

TMI2-422: added check for null value

---

src/main/java/gov/cabinetoffice/gap/adminbackend/controllers/SpotlightBatchController.java
src/main/java/gov/cabinetoffice/gap/adminbackend/services/GrantMandatoryQuestionService.java
src/main/java/gov/cabinetoffice/gap/adminbackend/services/SpotlightBatchService.java
src/test/java/gov/cabinetoffice/gap/adminbackend/controllers/SpotlightBatchControllerTest.java
src/test/java/gov/cabinetoffice/gap/adminbackend/services/GrantMandatoryQuestionServiceTest.java
src/test/java/gov/cabinetoffice/gap/adminbackend/services/SpotlightBatchServiceTest.java

Adds endpoint to download spotlight flies based grouped by orgType that had validation errors in Spotlight
TMI2-421: https://technologyprogramme.atlassian.net/browse/TMI2-421

TMI2-421 - Added missing call for spotlight validation error download

---

src/main/java/gov/cabinetoffice/gap/adminbackend/constants/SpotlightExports.java
src/main/java/gov/cabinetoffice/gap/adminbackend/controllers/SpotlightSubmissionController.java
src/main/java/gov/cabinetoffice/gap/adminbackend/controllers/SubmissionsController.java
src/main/java/gov/cabinetoffice/gap/adminbackend/services/SpotlightSubmissionService.java
src/main/java/gov/cabinetoffice/gap/adminbackend/services/SubmissionsService.java
src/test/java/gov/cabinetoffice/gap/adminbackend/controllers/SpotlightSubmissionControllerTest.java
src/test/java/gov/cabinetoffice/gap/adminbackend/controllers/SubmissionsControllerTest.java
src/test/java/gov/cabinetoffice/gap/adminbackend/services/SubmissionsServiceTest.java

Only allows 999 rows per file and when it exceeds this, it creates a new file. All these files are then zipped so that they can be downloaded together.
Updated the required checks download to download a zip file instead of just an .xlsx file to accommodate for multiple files if submissions exceeds 999
TMI2-524: https://technologyprogramme.atlassian.net/browse/TMI2-524

TMI2-524: spotlight export row limit

---

src/main/java/gov/cabinetoffice/gap/adminbackend/services/GrantAdvertService.java
src/test/java/gov/cabinetoffice/gap/adminbackend/services/GrantAdvertServiceTest.java

The user was able to create multiple adverts for a scheme. Now inside the create method, we check if an advert already exists, if it does, we just update it and only create a new advert if one does not exist
TMI2-525: https://technologyprogramme.atlassian.net/browse/TMI2-525

TMI2-524: check if advert exists before creating a new one

---

src/main/java/gov/cabinetoffice/gap/adminbackend/controllers/SubmissionsController.java
src/test/java/gov/cabinetoffice/gap/adminbackend/controllers/SubmissionsControllerTest.java

in one of the endpoint used by the lambdas, we are calling user service too.
in this call we were passing the same AuthorizationSecret used by the lambda which now is encrypted.
We are now passing the non encrypted authorization value to the user service request(how it was).

fix call to user-service

---

src/main/java/gov/cabinetoffice/gap/adminbackend/schedulers/GrantAdvertsScheduler.java
src/main/resources/db/migration/V1_83__scheduled_publishing_include_time.sql

Ticket [GAP-2359](https://technologyprogramme.atlassian.net/jira/software/projects/GAP/boards/216?selectedIssue=GAP-2359)
- Refactored DB publishing view to take into account time
- Also treats the timestamp as Europe/London time
- Scheduled job default cron runs hourly
- Removed scheduled job zone as it will use the servers local zone by default (and run hourly regardless)
- Updated scheduled job sandbox cron time AWS secret to also be hourly
[GAP-2359]: https://technologyprogramme.atlassian.net/browse/GAP-2359?atlOrigin=eyJpIjoiN …

GAP-2359: Publish/unpublish ads includes time

---

src/main/java/gov/cabinetoffice/gap/adminbackend/services/ApplicationFormService.java

Ticket [GAP-2396](https://technologyprogramme.atlassian.net/browse/GAP-2396)
- Adding hard coded validation for maxWords
- Sadly cant make use of the in built validator as a significant refactor of several core aspects of the app would need to be done to change validation from a Map<String, Object> to a DTO with validation annotations
- Raised https://technologyprogramme.atlassian.net/browse/GAP-2429 for this
https://github.com/cabinetoffice/gap-find-apply-web/assets/101722961/160b489e-2f87-422f-babe-14e0f5c08eb0
[GAP-2396]: …

GAP-2396: Validate max words field in patch question endpoint

---

src/main/java/gov/cabinetoffice/gap/adminbackend/dtos/UserDTO.java

Changes in this PR:
- Updates UserDto to include roles
This is consumed by apply frontend and uses it to render the nav bar on the admin dashboard if a user has the tech support role
Related PRs:
Other PRs included in this change:
https://github.com/cabinetoffice/gap-find-api-admin/pull/59
https://github.com/cabinetoffice/gap-find-apply-web/pull/311

Adds roles to user dto

---

.github/workflows/feature.yml
src/main/java/gov/cabinetoffice/gap/adminbackend/entities/GrantAdmin.java
src/main/java/gov/cabinetoffice/gap/adminbackend/entities/SchemeEntity.java
src/main/java/gov/cabinetoffice/gap/adminbackend/security/AuthManager.java
src/main/java/gov/cabinetoffice/gap/adminbackend/services/SchemeService.java
src/main/resources/db/migration/V1_95__add_new_scheme_editors_table.sql
src/main/resources/db/migration/V1_95__add_new_scheme_permissions_table.sql
src/test/java/gov/cabinetoffice/gap/adminbackend/services/FeedbackServiceTest.java
src/test/java/gov/cabinetoffice/gap/adminbackend/services/GrantAdvertServiceTest.java
src/test/java/gov/cabinetoffice/gap/adminbackend/services/SchemeServiceTest.java
src/test/java/gov/cabinetoffice/gap/adminbackend/testdata/LoginTestData.java
src/test/java/gov/cabinetoffice/gap/adminbackend/testdata/SchemeTestData.java
src/test/java/gov/cabinetoffice/gap/adminbackend/testdata/generators/RandomGrantAdvertGenerators.java

Added join table (scheme_permissions) and additional functionality in SchemeService to add a single admin to this repository.
GAP-2447: https://technologyprogramme.atlassian.net/browse/GAP-2447

GAP-2447-owner-editor-data-model

---

src/main/java/gov/cabinetoffice/gap/adminbackend/controllers/GrantExportController.java
src/main/java/gov/cabinetoffice/gap/adminbackend/services/GrantExportService.java
src/test/java/gov/cabinetoffice/gap/adminbackend/controllers/GrantExportControllerTest.java
src/test/java/gov/cabinetoffice/gap/adminbackend/services/GrantExportServiceTest.java

Adds an endpoint to get the number of grant exports with a given status
This should also cover this ticket: https://technologyprogramme.atlassian.net/browse/TMI2-638
TMI2-644: https://technologyprogramme.atlassian.net/browse/TMI2-644

TMI2-644 get failed grant export count

---

src/main/java/gov/cabinetoffice/gap/adminbackend/entities/GrantAdmin.java
src/main/java/gov/cabinetoffice/gap/adminbackend/entities/SchemeEntity.java

Publishing adverts was actually successfully updating the database, but fell over as the endpoint returns a raw `GrantAdvert` entity. Jackson attempts to serialize its relationship like the schemeEditors (which were lazy loaded, and therefore dont exist) and falls over. We use an annotation: `@JsonIgnoreProperties` to tell jackson to ignore this relationship.
This code didnt break in other places as endpoints should not return raw entities. If this was mapped to a DTO, it would have not fallen over.
https://github.com/cabinetoffice/gap-find-admin-backend/assets/101722961/007c0df0-e973-47c8-a1d5-83611f80bc70

GAP-2481: Fix publishing adverts

---

src/main/java/gov/cabinetoffice/gap/adminbackend/controllers/GrantAdvertController.java
src/main/java/gov/cabinetoffice/gap/adminbackend/dtos/grantadvert/FullGrantAdvertPublishingInformationResponseDTO.java
src/main/java/gov/cabinetoffice/gap/adminbackend/dtos/grantadvert/GetGrantAdvertPublishingInformationResponseDTO.java
src/main/java/gov/cabinetoffice/gap/adminbackend/mappers/GrantAdvertMapper.java
src/main/java/gov/cabinetoffice/gap/adminbackend/services/GrantAdvertService.java
src/main/java/gov/cabinetoffice/gap/adminbackend/services/UserService.java
src/test/java/gov/cabinetoffice/gap/adminbackend/controllers/GrantAdvertControllerTest.java
src/test/java/gov/cabinetoffice/gap/adminbackend/services/GrantAdvertServiceTest.java
src/test/java/gov/cabinetoffice/gap/adminbackend/testdata/generators/RandomGrantAdvertGenerators.java

Adds lastUpdatedBy field to publishing info DTO
https://technologyprogramme.atlassian.net/jira/software/projects/GAP/boards/216?selectedIssue=GAP-2432
related pr: https://github.com/cabinetoffice/gap-find-apply-web/pull/358

GAP-2432: add lastUpdatedBy email to advert publishing info

---

src/main/java/gov/cabinetoffice/gap/adminbackend/controllers/ApplicationFormController.java
src/main/java/gov/cabinetoffice/gap/adminbackend/services/ApplicationFormService.java
src/test/java/gov/cabinetoffice/gap/adminbackend/controllers/ApplicationFormControllerTest.java
src/test/java/gov/cabinetoffice/gap/adminbackend/services/ApplicationFormServiceTest.java

Adds an endpoint to get application form status to be used in the frontend to redirect admins who try to edit an application form with PUBLISHED status
TMI2-616: https://technologyprogramme.atlassian.net/browse/TMI2-616

TMI@-616: get application form status

---

src/main/java/gov/cabinetoffice/gap/adminbackend/controllers/ApplicationFormSectionsController.java
src/main/java/gov/cabinetoffice/gap/adminbackend/controllers/ControllerExceptionHandler.java
src/main/java/gov/cabinetoffice/gap/adminbackend/dtos/application/PatchSectionDTO.java
src/main/java/gov/cabinetoffice/gap/adminbackend/entities/ApplicationFormEntity.java
src/main/java/gov/cabinetoffice/gap/adminbackend/exceptions/ConflictException.java
src/main/java/gov/cabinetoffice/gap/adminbackend/services/ApplicationFormSectionService.java
src/main/java/gov/cabinetoffice/gap/adminbackend/utils/ApplicationFormUtils.java
src/test/java/gov/cabinetoffice/gap/adminbackend/controllers/ApplicationFormSectionsControllerTest.java
src/test/java/gov/cabinetoffice/gap/adminbackend/services/ApplicationFormSectionServiceTest.java
src/test/java/gov/cabinetoffice/gap/adminbackend/utils/ApplicationFormUtilsTest.java

[GAP-2454](https://technologyprogramme.atlassian.net/browse/GAP-2454)
with [GAP-2457](https://technologyprogramme.atlassian.net/browse/GAP-2457) to prove it works
Off the back of https://github.com/cabinetoffice/gap-find-admin-backend/pull/232 this is a new PR which does not include the renaming of version to revision to prevent conflicts
https://github.com/cabinetoffice/gap-find-apply-web/pull/374
[GAP-2454]: https://technologyprogramme.atlassian.net/browse/GAP-2454?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJ …

GAP-2454/GAP-2457: Multiple Editors with Section Title

---

src/main/java/gov/cabinetoffice/gap/adminbackend/controllers/ApplicationFormSectionsController.java
src/main/java/gov/cabinetoffice/gap/adminbackend/services/ApplicationFormSectionService.java
src/test/java/gov/cabinetoffice/gap/adminbackend/controllers/ApplicationFormSectionsControllerTest.java
src/test/java/gov/cabinetoffice/gap/adminbackend/services/ApplicationFormSectionServiceTest.java

[GAP-2460](https://technologyprogramme.atlassian.net/browse/GAP-2460)
Multiple editors - prevent deleting application section if version is outdated
https://github.com/cabinetoffice/gap-find-apply-web/pull/383
[GAP-2460]: https://technologyprogramme.atlassian.net/browse/GAP-2460?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

GAP-2460 | Multiple editors - delete section

---

src/main/java/gov/cabinetoffice/gap/adminbackend/dtos/application/ApplicationFormQuestionDTO.java
src/main/java/gov/cabinetoffice/gap/adminbackend/dtos/application/questions/QuestionSessionDTO.java
src/main/java/gov/cabinetoffice/gap/adminbackend/services/ApplicationFormService.java
src/test/java/gov/cabinetoffice/gap/adminbackend/testdata/ApplicationFormTestData.java

Covers [GAP-2458](https://technologyprogramme.atlassian.net/browse/GAP-2458), [GAP-2456](https://technologyprogramme.atlassian.net/browse/GAP-2456) and [GAP-2459](https://technologyprogramme.atlassian.net/browse/GAP-2459)
requires version to be passed when patching question and compares to value saved in db before allowing patch to continue
https://github.com/cabinetoffice/gap-find-apply-web/pull/385
[GAP-2458]: https://technologyprogramme.atlassian.net/browse/GAP-2458?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiL …

GAP-2458: Multiple Editors - edit question

---

src/main/java/gov/cabinetoffice/gap/adminbackend/listeners/SchemeUpdateListener.java
src/main/java/gov/cabinetoffice/gap/adminbackend/services/ApplicationFormService.java
src/main/java/gov/cabinetoffice/gap/adminbackend/services/GrantAdvertService.java
src/test/java/gov/cabinetoffice/gap/adminbackend/services/GrantAdvertServiceTest.java

There was a requirement to stop super admins appearing in the last updated by fields if they were performing actions such as changing ownership of a grant. 
[GAP-2501](https://technologyprogramme.atlassian.net/jira/software/projects/GAP/boards/216?selectedIssue=GAP-2501)
Added a check to see whether actions being performed on a grant were performed by someone listed as an editor. If they were then we log the dates. If not then we don't. 
[GAP-2501]: https://technologyprogramme.atlassian.net/browse/GAP-2501?atlOrig …

GAP-2501 - stopping super admins appearing in last updated by/date fields

---

src/main/java/gov/cabinetoffice/gap/adminbackend/services/ApplicationFormService.java
src/test/java/gov/cabinetoffice/gap/adminbackend/services/ApplicationFormServiceTest.java
src/test/java/gov/cabinetoffice/gap/adminbackend/testdata/ApplicationFormTestData.java

[GAP-2455](https://technologyprogramme.atlassian.net/jira/software/projects/GAP/boards/216?selectedIssue=GAP-2455)
[Related pr (frontend)](https://github.com/cabinetoffice/gap-find-apply-web/pull/393)
Adds logic to the add question service: now throws a conflict exception when the queried section doesn't exist. (It must have been deleted by another editor)
[GAP-2455]: https://technologyprogramme.atlassian.net/browse/GAP-2455?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

GAP-2455 | handle multiple editors section deleted

---

src/main/java/gov/cabinetoffice/gap/adminbackend/services/pages/PagesAdvertService.java
src/test/java/gov/cabinetoffice/gap/adminbackend/services/pages/PagesAdvertServiceTest.java

Changes advert preview date format for midnight dates to be 1 minute past midnight for opening dates and 1 minute before midnight for closing dates. The text "Midnight" has also been added before the date
TMI2-721: https://technologyprogramme.atlassian.net/browse/TMI2-721

TMI2-721: changes preview date format for midnight times

---

src/main/java/gov/cabinetoffice/gap/adminbackend/config/JacksonConfig.java
src/main/java/gov/cabinetoffice/gap/adminbackend/config/OpenSearchConfig.java
src/main/java/gov/cabinetoffice/gap/adminbackend/services/GrantAdvertService.java
src/main/java/gov/cabinetoffice/gap/adminbackend/services/OpenSearchService.java
src/main/resources/application.properties
src/test/java/gov/cabinetoffice/gap/adminbackend/services/GrantAdvertServiceTest.java
src/test/java/gov/cabinetoffice/gap/adminbackend/services/OpenSearchServiceTest.java

Ticket [GAP-2487](https://technologyprogramme.atlassian.net/jira/software/projects/GAP/boards/216?selectedIssue=GAP-2487)
- Replacing contentfuls webhooks that update elastic search with manual api calls from our backend
- Prevents race conditions in the webhooks
- Prevents async nature of webhooks sometimes taking 15 mins to trigger
TODO:
- Refactor cypress to seed elastic when seeding contentful
- Infra PR to add secrets to admin backend task def
https://github.com/cabinetoffice/gap-find-admin-backend/assets/101722961/61c3467e-94 …

GAP-2487: Replace contentful webhooks with synchronous api call

---

src/main/java/gov/cabinetoffice/gap/adminbackend/controllers/SubmissionsController.java
src/main/java/gov/cabinetoffice/gap/adminbackend/services/SubmissionsService.java
src/test/java/gov/cabinetoffice/gap/adminbackend/controllers/SubmissionsControllerTest.java
src/test/java/gov/cabinetoffice/gap/adminbackend/services/SubmissionsServiceTest.java

Remove the existing private method which retrieves the user's email from the user service from the submission service & use the existing method in the UserServiceClient which is already setup to use the encrypted secret.

Bugfix: Refactor submission export to use existing UserServiceClient to retrieve user email by sub

---

src/main/java/gov/cabinetoffice/gap/adminbackend/services/ApplicationFormService.java
src/main/java/gov/cabinetoffice/gap/adminbackend/utils/ApplicationFormUtils.java
src/test/java/gov/cabinetoffice/gap/adminbackend/services/ApplicationFormServiceTest.java

https://technologyprogramme.atlassian.net/jira/software/projects/GAP/boards/216?selectedIssue=GAP-2526
related pr: https://github.com/cabinetoffice/gap-find-apply-web/pull/421
- Extracts multiple editor validation, 
- Application service now throws a conflict exception if the section doesn't exist when retrieving a question

Multiple editors - handle editing recently deleted section

---

src/main/java/gov/cabinetoffice/gap/adminbackend/controllers/ApplicationFormController.java
src/main/java/gov/cabinetoffice/gap/adminbackend/repositories/GrantAdvertRepository.java
src/main/java/gov/cabinetoffice/gap/adminbackend/services/ApplicationFormService.java
src/main/java/gov/cabinetoffice/gap/adminbackend/services/GrantAdvertService.java
src/test/java/gov/cabinetoffice/gap/adminbackend/controllers/ApplicationFormControllerTest.java

Noticed the scheduled job consistently fails to unpublish an application form. As this endpoint does not log anything upon exceptions thrown in certain places its impossible to be sure why, but the data looks sensible.
- Adding a log upon any exception
- Eagerly fetching scheme so we can grab the schemesId from the advert entity

Fix schedule unpublish application forms and add logs upon failure

---

src/main/java/gov/cabinetoffice/gap/adminbackend/dtos/grantadvert/GetGrantAdvertPublishingInformationResponseDTO.java
src/main/java/gov/cabinetoffice/gap/adminbackend/entities/GrantAdvert.java
src/main/java/gov/cabinetoffice/gap/adminbackend/services/GrantAdvertService.java
src/test/java/gov/cabinetoffice/gap/adminbackend/controllers/GrantAdvertControllerTest.java
src/test/java/gov/cabinetoffice/gap/adminbackend/services/GrantAdvertServiceTest.java

Our logic converting the times to `Instant` types was stripping the timezone without adjusting the value; this change uses `LocalDateTime` for these values instead, allowing postgres to convert the values for us when saving and retrieving from the database.
>For timestamp with time zone, the internally stored value is always in UTC (Universal Coordinated Time, traditionally known as Greenwich Mean Time, GMT). An input value that has an explicit time zone specified is converted to UTC using the appropriate offset for that time zone. If no time zone is stated in the input string, then it is assumed to be in the time zone indicated by the system's [TimeZone](https://www.postgresql.org/docs/current/runtime-config-client.html#GUC-TIMEZONE) parameter, and is converted to UTC using the offset …

use LocalDateTime for grant opening and closing times

---

src/main/java/gov/cabinetoffice/gap/adminbackend/controllers/GrantAdvertController.java
src/main/java/gov/cabinetoffice/gap/adminbackend/dtos/pages/AdvertSummaryPageDTO.java
src/main/java/gov/cabinetoffice/gap/adminbackend/services/GrantAdvertService.java
src/main/java/gov/cabinetoffice/gap/adminbackend/services/pages/PagesAdvertService.java
src/test/java/gov/cabinetoffice/gap/adminbackend/services/GrantAdvertServiceTest.java

if a user sets a grant to publish less than an hour in the past (IE, immediately) during daylight savings time then the "schedule" button will appear as the server operates on UTC and the conversion that determines whether the "schedule" button should appear or not does not take this potential difference in timezones into account. This change adds better handling of absolute date times. 
[GAP 2592](https://technologyprogramme.atlassian.net/jira/software/projects/GAP/boards/216?selectedIssue=GAP-2592)
see above

GAP-2592: daylight savings causing time to be off by one hour

---

src/main/java/gov/cabinetoffice/gap/adminbackend/services/OpenSearchService.java
src/test/java/gov/cabinetoffice/gap/adminbackend/services/OpenSearchServiceTest.java

If a grant contained rich text fields then it was silently dying inside the application because of a setting we had switched on inside our jackson data mapper. We've replaced this method of creating JSON with a method that just directly fetches it from contentful using HTTP. 
[GAP-2586
](https://technologyprogramme.atlassian.net/jira/software/projects/GAP/boards/216?selectedIssue=GAP-2586)
Changed the way we create the JSON that is sent to open search. 

GAP-2586: Grants with rich text not publishing to open search

---

src/main/java/gov/cabinetoffice/gap/adminbackend/constants/ValidationMaps.java
src/main/java/gov/cabinetoffice/gap/adminbackend/mappers/ApplicationFormMapper.java
src/test/java/gov/cabinetoffice/gap/adminbackend/services/ApplicationFormServiceTest.java
src/test/java/gov/cabinetoffice/gap/adminbackend/testdata/ApplicationFormTestData.java

https://technologyprogramme.atlassian.net/browse/GAP-2532
If response type is changing in a question, reset the validation with the incoming

Gap 2532/grant validation clean up

---

src/main/java/gov/cabinetoffice/gap/adminbackend/repositories/ApplicationFormRepository.java
src/main/java/gov/cabinetoffice/gap/adminbackend/repositories/GrantAdvertRepository.java
src/main/java/gov/cabinetoffice/gap/adminbackend/services/ApplicationFormService.java
src/main/java/gov/cabinetoffice/gap/adminbackend/services/GrantAdvertService.java
src/main/java/gov/cabinetoffice/gap/adminbackend/services/SchemeService.java
src/test/java/gov/cabinetoffice/gap/adminbackend/services/GrantAdvertServiceTest.java
src/test/java/gov/cabinetoffice/gap/adminbackend/services/SchemeServiceTest.java

Fixes admin reference clean up

---

src/main/java/gov/cabinetoffice/gap/adminbackend/controllers/UserController.java

use lowercase email to fetch user

---

src/main/java/gov/cabinetoffice/gap/adminbackend/controllers/SchemeEditorController.java

amend schemeeditorcontroller
