- src/main/resources/db/migration/V1_58__grant_beneficiary_add_org_fields.sql
creates migration to add organisation fields to grant beneficiary table
> create grant beneficiary migration

- src/main/java/gov/cabinetoffice/gap/adminbackend/controllers/LoginController.java
- src/main/java/gov/cabinetoffice/gap/adminbackend/security/AuthManager.java
Related prs
- https://github.com/cabinetoffice/gap-find-apply-web/pull/49
- https://github.com/cabinetoffice/gap-user-service/pull/80
> GAP-1928 - add logout

- src/main/java/gov/cabinetoffice/gap/adminbackend/controllers/SubmissionsController.java
- src/main/java/gov/cabinetoffice/gap/adminbackend/utils/XlsxGenerator.java
- Adding logging so we can see how long the export takes
- Removing code that formats the excel sheet as this was causing an unacceptable performance problem
https://technologyprogramme.atlassian.net/browse/GAP-2228
> Fixing performance problems with required checks export

- src/main/java/gov/cabinetoffice/gap/adminbackend/controllers/ApplicationFormController.java
- src/main/java/gov/cabinetoffice/gap/adminbackend/repositories/ApplicationFormRepository.java
- src/main/java/gov/cabinetoffice/gap/adminbackend/security/WebSecurityConfig.java
- src/main/java/gov/cabinetoffice/gap/adminbackend/services/ApplicationFormSectionService.java
- src/main/java/gov/cabinetoffice/gap/adminbackend/services/ApplicationFormService.java
- src/main/java/gov/cabinetoffice/gap/adminbackend/utils/ApplicationFormUtils.java
- src/test/java/gov/cabinetoffice/gap/adminbackend/controllers/ApplicationFormControllerTest.java
- src/test/java/gov/cabinetoffice/gap/adminbackend/services/ApplicationFormSectionServiceTest.java
- src/test/java/gov/cabinetoffice/gap/adminbackend/services/ApplicationFormServiceTest.java
- src/test/java/gov/cabinetoffice/gap/adminbackend/testdata/ApplicationFormTestData.java
- src/test/java/gov/cabinetoffice/gap/adminbackend/utils/ApplicationFormUtilsTest.java
Cherrypicks the squashed commit from develop
> Releases GAP-2218 to QA

- .github/workflows/feature.yml
- .github/workflows/promoteToProd.yml
- .github/workflows/pushImage.yml
- src/main/java/gov/cabinetoffice/gap/adminbackend/services/ApplicationFormService.java
Simultaneously creates docker image, and tests app. Deploys docker image of both stages pass.
- Upgrading login to ecr to v2 which solves a security issue
> Improve cd pipelines

- src/main/java/gov/cabinetoffice/gap/adminbackend/controllers/SchemeController.java
- src/main/java/gov/cabinetoffice/gap/adminbackend/repositories/SchemeRepository.java
- src/main/java/gov/cabinetoffice/gap/adminbackend/security/AuthManager.java
- src/main/java/gov/cabinetoffice/gap/adminbackend/services/SchemeService.java
- src/test/java/gov/cabinetoffice/gap/adminbackend/controllers/SchemeControllerTest.java
- src/test/java/gov/cabinetoffice/gap/adminbackend/services/SchemeServiceTest.java
- Improving our role based access so we can use annotations like: `@PreAuthorize("hasRole('SUPER_ADMIN')")`
- Adding an endpoint to fetch all of an admins schemes
> GAP-1784: Transfer ownership - get admins schemes

- pom.xml
- src/main/java/gov/cabinetoffice/gap/adminbackend/controllers/ApplicationFormController.java
- src/main/java/gov/cabinetoffice/gap/adminbackend/controllers/SchemeController.java
- src/main/java/gov/cabinetoffice/gap/adminbackend/controllers/UserController.java
- src/main/java/gov/cabinetoffice/gap/adminbackend/dtos/CheckNewAdminEmailDto.java
- src/main/java/gov/cabinetoffice/gap/adminbackend/dtos/schemes/SchemeDTO.java
- src/main/java/gov/cabinetoffice/gap/adminbackend/mappers/SchemeMapper.java
- src/main/java/gov/cabinetoffice/gap/adminbackend/repositories/ApplicationFormRepository.java
- src/main/java/gov/cabinetoffice/gap/adminbackend/repositories/GrantAdminRepository.java
- src/main/java/gov/cabinetoffice/gap/adminbackend/repositories/GrantAdvertRepository.java
- src/main/java/gov/cabinetoffice/gap/adminbackend/services/ApplicationFormService.java
- src/main/java/gov/cabinetoffice/gap/adminbackend/services/GrantAdvertService.java
- src/main/java/gov/cabinetoffice/gap/adminbackend/services/SchemeService.java
- src/main/java/gov/cabinetoffice/gap/adminbackend/services/UserService.java
- src/main/java/gov/cabinetoffice/gap/adminbackend/utils/HelperUtils.java
- src/test/java/gov/cabinetoffice/gap/adminbackend/controllers/SchemeControllerTest.java
- src/test/java/gov/cabinetoffice/gap/adminbackend/controllers/UserControllerTest.java
- src/test/java/gov/cabinetoffice/gap/adminbackend/services/ApplicationFormServiceTest.java
- src/test/java/gov/cabinetoffice/gap/adminbackend/services/GrantAdvertServiceTest.java
- src/test/java/gov/cabinetoffice/gap/adminbackend/services/SchemeServiceTest.java
- src/test/java/gov/cabinetoffice/gap/adminbackend/services/UserServiceTest.java
- Adding endpoint to validate a new admins email
- Adding an endpoint to patch the createdBy columns related to a scheme
- Improving RBAC
Depends on:
- https://github.com/cabinetoffice/gap-user-service/pull/147
https://github.com/cabinetoffice/gap-find-admin-backend/assets/101722961/f3d583a0-573c-4e38-9840-f4831ff27787
> GAP-1784 - Transfer ownership

- src/main/java/gov/cabinetoffice/gap/adminbackend/annotations/SpotlightPublisherHeaderValidator.java
- src/main/java/gov/cabinetoffice/gap/adminbackend/config/SpotlightPublisherConfigProperties.java
- src/main/java/gov/cabinetoffice/gap/adminbackend/config/SpotlightPublisherInterceptor.java
- src/main/java/gov/cabinetoffice/gap/adminbackend/controllers/SpotlightBatchController.java
- src/main/java/gov/cabinetoffice/gap/adminbackend/entities/SpotlightBatch.java
- src/main/java/gov/cabinetoffice/gap/adminbackend/entities/SpotlightSubmission.java
- src/main/java/gov/cabinetoffice/gap/adminbackend/enums/SpotlightBatchStatus.java
- src/main/java/gov/cabinetoffice/gap/adminbackend/enums/SpotlightSubmissionStatus.java
- src/main/java/gov/cabinetoffice/gap/adminbackend/repositories/SpotlightBatchRepository.java
- src/main/java/gov/cabinetoffice/gap/adminbackend/repositories/SpotlightSubmissionRepository.java
- src/main/java/gov/cabinetoffice/gap/adminbackend/security/WebSecurityConfig.java
- src/main/java/gov/cabinetoffice/gap/adminbackend/security/interceptors/AuthorizationHeaderInterceptor.java
- src/main/java/gov/cabinetoffice/gap/adminbackend/services/SpotlightBatchService.java
- src/main/java/gov/cabinetoffice/gap/adminbackend/services/SpotlightSubmissionService.java
- src/main/resources/application.properties
- src/test/java/gov/cabinetoffice/gap/adminbackend/controllers/SpotlightBatchControllerTest.java
- src/test/java/gov/cabinetoffice/gap/adminbackend/security/interceptors/AuthorizationHeaderInterceptorTest.java
- src/test/java/gov/cabinetoffice/gap/adminbackend/services/SpotlightBatchServiceTest.java
- src/test/java/gov/cabinetoffice/gap/adminbackend/services/SpotlightSubmissionServiceTest.java
- add spotlightBatch controller and service, 
- spotlightSubmission service, 
- add unit test coverage,
-  add interceptor for api calls done from spotlight publisher lambda
> Spotlight batch preparation

- src/main/resources/db/migration/V1_75__drop_created_by_and_updated_by_on_spotlight_tables.sql
Removing redundant columns from the spotlight check tables.
> TMI2-396: Add submissions to Spotlight

- src/main/java/gov/cabinetoffice/gap/adminbackend/controllers/SpotlightBatchController.java
- src/main/java/gov/cabinetoffice/gap/adminbackend/controllers/SpotlightSubmissionController.java
- src/test/java/gov/cabinetoffice/gap/adminbackend/controllers/SpotlightBatchControllerTest.java
- src/test/java/gov/cabinetoffice/gap/adminbackend/controllers/SpotlightSubmissionControllerTest.java
Add controller for spotlightSubmission
+ add some logs
> add controller for spotlightSubmission

- src/main/java/gov/cabinetoffice/gap/adminbackend/controllers/ApplicationFormController.java
- src/main/java/gov/cabinetoffice/gap/adminbackend/controllers/SchemeController.java
- src/main/java/gov/cabinetoffice/gap/adminbackend/services/ApplicationFormService.java
- src/test/java/gov/cabinetoffice/gap/adminbackend/controllers/ApplicationFormControllerTest.java
- src/test/java/gov/cabinetoffice/gap/adminbackend/controllers/SchemeControllerTest.java
- src/test/java/gov/cabinetoffice/gap/adminbackend/services/ApplicationFormServiceTest.java
https://technologyprogramme.atlassian.net/browse/GAP-2300
> Removes exception when no application found in scheduled advert unpublish cron

- src/main/java/gov/cabinetoffice/gap/adminbackend/controllers/GrantMandatoryQuestionsController.java
- src/main/java/gov/cabinetoffice/gap/adminbackend/repositories/GrantMandatoryQuestionRepository.java
- src/main/java/gov/cabinetoffice/gap/adminbackend/services/GrantMandatoryQuestionService.java
- src/test/java/gov/cabinetoffice/gap/adminbackend/controllers/MandatoryQuestionsControllerTest.java
- src/test/java/gov/cabinetoffice/gap/adminbackend/services/GrantMandatoryQuestionServiceTest.java
Adds endpoint to check if there are completed mandatory questions within a specified org type for spotlight downloads
TMI2-422 - https://technologyprogramme.atlassian.net/browse/TMI2-422
> TMI2-422: checks if there are completed mandatory questions for spotlight

- src/main/java/gov/cabinetoffice/gap/adminbackend/security/WebSecurityConfig.java
> exclude s3-object-key route from auth

- src/main/java/gov/cabinetoffice/gap/adminbackend/services/SubmissionsService.java
- src/test/java/gov/cabinetoffice/gap/adminbackend/services/SubmissionsServiceTest.java
> fix export filename extraction

- src/main/java/gov/cabinetoffice/gap/adminbackend/enums/GrantMandatoryQuestionFundingLocation.java
Backend for [TMI2-459](https://technologyprogramme.atlassian.net/browse/TMI2-459)
[TMI2-459]: https://technologyprogramme.atlassian.net/browse/TMI2-459?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> TMI2-459 - Added brackets to East England location

- src/main/java/gov/cabinetoffice/gap/adminbackend/services/SpotlightBatchService.java
- src/main/java/gov/cabinetoffice/gap/adminbackend/services/SpotlightSubmissionService.java
- src/test/java/gov/cabinetoffice/gap/adminbackend/services/SpotlightBatchServiceTest.java
- src/test/java/gov/cabinetoffice/gap/adminbackend/services/SpotlightSubmissionServiceTest.java
Refactors processSpotlightResponse method to increase readability
> Tmi2 418 process spotlight responses v2

- src/main/java/gov/cabinetoffice/gap/adminbackend/security/WebSecurityConfig.java
- src/main/resources/db/migration/V1_76__adding_event-service_tables.sql
> fix whitelisht

- src/main/java/gov/cabinetoffice/gap/adminbackend/security/AuthManager.java
[Ticket 2319
](https://technologyprogramme.atlassian.net/jira/software/projects/GAP/boards/216?selectedIssue=GAP-2319)
Based on [this](https://serverfault.com/questions/300222/invalidate-all-sessions-at-application-reload#:~:text=all%20such%20attributes%20MUST%20implement%20the%20java.io.Serializable%20interface), I believe we regressed retaining sessions after creating a non serializable list as part of the admin session. This change ensures we use an array list.
Will test in sandbox after deploying.
> GAP-2319: Fixing sessions invalidating after restarting the app

- src/main/java/gov/cabinetoffice/gap/adminbackend/services/SpotlightBatchService.java
> Temporary additional logging of Spotlight requests

- src/main/java/gov/cabinetoffice/gap/adminbackend/services/SpotlightBatchService.java
> Re-ordering some logic to prevent errors

- src/main/java/gov/cabinetoffice/gap/adminbackend/mappers/CustomMandatoryQuestionMapper.java
- src/test/java/gov/cabinetoffice/gap/adminbackend/mappers/CustomMandatoryQuestionMapperTest.java
> Adding non limited companies to enum

- src/main/java/gov/cabinetoffice/gap/adminbackend/services/SnsService.java
- src/main/java/gov/cabinetoffice/gap/adminbackend/services/SpotlightBatchService.java
- src/test/java/gov/cabinetoffice/gap/adminbackend/services/SnsServiceTest.java
- src/test/java/gov/cabinetoffice/gap/adminbackend/services/SpotlightBatchServiceTest.java
Sends a support email to [findagrant@cabinetoffice.gov.uk](mailto:findagrant@cabinetoffice.gov.uk) when any 5xx error is returned from spotlight.
Here is the [SNS topic](https://eu-west-2.console.aws.amazon.com/sns/v3/home?region=eu-west-2#/topic/arn:aws:sns:eu-west-2:801347364784:gap-sandbox-spotlight-support)
TMI2-453: https://technologyprogramme.atlassian.net/browse/TMI2-453
> TMI2-453: Sends spotlight validation error support email

- src/main/java/gov/cabinetoffice/gap/adminbackend/controllers/SpotlightBatchController.java
> Adding additional logging

- src/main/java/gov/cabinetoffice/gap/adminbackend/controllers/SpotlightBatchController.java
- src/main/java/gov/cabinetoffice/gap/adminbackend/services/SpotlightBatchService.java
- src/main/resources/application.properties
- src/test/java/gov/cabinetoffice/gap/adminbackend/controllers/SpotlightBatchControllerTest.java
> Tmi2 468/fix batch size issue

- src/main/java/gov/cabinetoffice/gap/adminbackend/controllers/SchemeController.java
- src/main/java/gov/cabinetoffice/gap/adminbackend/controllers/UserController.java
- src/main/java/gov/cabinetoffice/gap/adminbackend/dtos/UpdateFundingOrgDto.java
- src/main/java/gov/cabinetoffice/gap/adminbackend/security/WebSecurityConfig.java
- src/main/java/gov/cabinetoffice/gap/adminbackend/services/SchemeService.java
- src/main/java/gov/cabinetoffice/gap/adminbackend/services/UserService.java
- src/test/java/gov/cabinetoffice/gap/adminbackend/controllers/SchemeControllerTest.java
- src/test/java/gov/cabinetoffice/gap/adminbackend/controllers/UserControllerTest.java
- src/test/java/gov/cabinetoffice/gap/adminbackend/services/SchemeServiceTest.java
- src/test/java/gov/cabinetoffice/gap/adminbackend/services/UserServiceTest.java
https://technologyprogramme.atlassian.net/browse/TMI2-474
Adds new endpoint to change fa user's funding org
Updates funding org when a users department is changed 
Changes scheme funding org to match user during change of ownership
> Adds endpoint to change funding org

- src/main/java/gov/cabinetoffice/gap/adminbackend/mappers/CustomMandatoryQuestionMapper.java
- src/test/java/gov/cabinetoffice/gap/adminbackend/mappers/CustomMandatoryQuestionMapperTest.java
Change Spotlight org type mapping for non-limited from company to sole trader
TMI2-480: https://technologyprogramme.atlassian.net/browse/TMI2-480
> TMI2-480: Map "non-limited" to Spotlights "sole trader"

- src/main/java/gov/cabinetoffice/gap/adminbackend/controllers/UserController.java
- src/main/java/gov/cabinetoffice/gap/adminbackend/repositories/GrantAdminRepository.java
- src/main/java/gov/cabinetoffice/gap/adminbackend/security/WebSecurityConfig.java
- src/main/java/gov/cabinetoffice/gap/adminbackend/services/UserService.java
- src/test/java/gov/cabinetoffice/gap/adminbackend/controllers/UserControllerTest.java
Modifies deletion url
Deletes gap user dependencies
https://technologyprogramme.atlassian.net/browse/TMI2-476
> fixes deletion of user

- src/main/java/gov/cabinetoffice/gap/adminbackend/controllers/SpotlightBatchController.java
- src/main/java/gov/cabinetoffice/gap/adminbackend/repositories/SpotlightBatchRepository.java
- src/main/java/gov/cabinetoffice/gap/adminbackend/services/SpotlightBatchService.java
- src/test/java/gov/cabinetoffice/gap/adminbackend/services/SpotlightBatchServiceTest.java
> fix query, and add more logs

- src/main/java/gov/cabinetoffice/gap/adminbackend/services/SpotlightBatchService.java
- src/test/java/gov/cabinetoffice/gap/adminbackend/services/SpotlightBatchServiceTest.java
> add logic to avoid Index 0 out of bounds error

- src/main/java/gov/cabinetoffice/gap/adminbackend/controllers/GrantMandatoryQuestionsController.java
- src/main/java/gov/cabinetoffice/gap/adminbackend/repositories/GrantMandatoryQuestionRepository.java
- src/main/java/gov/cabinetoffice/gap/adminbackend/services/GrantMandatoryQuestionService.java
- src/test/java/gov/cabinetoffice/gap/adminbackend/controllers/MandatoryQuestionsControllerTest.java
- src/test/java/gov/cabinetoffice/gap/adminbackend/services/GrantMandatoryQuestionServiceTest.java
* revert tmi2-496 changes
* format
> Tmi2 501/revert tmi2 496 changes (#129)

- src/main/java/gov/cabinetoffice/gap/adminbackend/config/CompletionStatisticsSchedulerConfigProperties.java
- src/main/java/gov/cabinetoffice/gap/adminbackend/schedulers/CompletionStatisticsScheduler.java
- src/main/resources/application.properties
- src/test/java/gov/cabinetoffice/gap/adminbackend/schedulers/CompletionStatisticsSchedulerTest.java
> Tn 154 trigger calculations scheduler

- src/main/java/gov/cabinetoffice/gap/adminbackend/controllers/GrantAdvertController.java
- src/test/java/gov/cabinetoffice/gap/adminbackend/controllers/GrantAdvertControllerTest.java
https://technologyprogramme.atlassian.net/browse/TD-108
The static analysis highlighted a potential XXE ( [XML External Entity](https://owasp.org/www-community/vulnerabilities/XML_External_Entity_(XXE)_Processing) ) vulnerability in the updatePage endpoint. 
Adding explicit @Produces and @Consumes annotations to prevent this.
> TD-108 XXE issue fix

- src/main/resources/db/migration/V1_81__adding_submission_complete_mandatory_sections_flag.sql
Ticket [GAP-2291](https://technologyprogramme.atlassian.net/jira/software/projects/GAP/boards/216?selectedIssue=GAP-2291)
- Adding a flag `mandatorySectionsCompleted` to submissions
[GAP-2291]: https://technologyprogramme.atlassian.net/browse/GAP-2291?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> GAP-2291: Adding mandatorySectionsCompleted flag db column

- src/main/java/gov/cabinetoffice/gap/adminbackend/services/GrantAdvertService.java
- src/main/java/gov/cabinetoffice/gap/adminbackend/validation/validators/AdvertPageResponseValidator.java
- src/test/java/gov/cabinetoffice/gap/adminbackend/services/GrantAdvertServiceTest.java
- src/test/java/gov/cabinetoffice/gap/adminbackend/validation/validators/AdvertPageResponseValidatorTest.java
Adds logic to handle opening and closing times for grant adverts
Handles case where closing date is 23:59 (as per design). This will set time to 00:00 and increment day by 1
https://technologyprogramme.atlassian.net/browse/GAP-2355
> Adds logic to handle opening and closing times for grant adverts

- src/main/java/gov/cabinetoffice/gap/adminbackend/controllers/GrantMandatoryQuestionsController.java
- src/main/java/gov/cabinetoffice/gap/adminbackend/controllers/SpotlightSubmissionController.java
- src/main/java/gov/cabinetoffice/gap/adminbackend/repositories/SubmissionRepository.java
- src/main/java/gov/cabinetoffice/gap/adminbackend/services/SubmissionsService.java
- src/test/java/gov/cabinetoffice/gap/adminbackend/controllers/MandatoryQuestionsControllerTest.java
- src/test/java/gov/cabinetoffice/gap/adminbackend/controllers/SpotlightSubmissionControllerTest.java
- src/test/java/gov/cabinetoffice/gap/adminbackend/services/SubmissionsServiceTest.java
the `last_required_checks_export` field in the `grant_submissions` table is now only be updated for submissions that are in progress and being updated for both V1 and V2 because it was previously only updating for V1
TMI2-594: https://technologyprogramme.atlassian.net/browse/TMI2-594
> TMI2-594: last required checks export update

- .github/workflows/promoteToProd.yml
- .github/workflows/pushImage.yml
> Running actions as github role rather than under access key and secret

- src/main/java/gov/cabinetoffice/gap/adminbackend/controllers/UserController.java
- src/main/java/gov/cabinetoffice/gap/adminbackend/dtos/user/CreateTechSupportUserDto.java
- src/main/java/gov/cabinetoffice/gap/adminbackend/entities/TechSupportUser.java
- src/main/java/gov/cabinetoffice/gap/adminbackend/repositories/TechSupportUserRepository.java
- src/main/java/gov/cabinetoffice/gap/adminbackend/security/WebSecurityConfig.java
- src/main/java/gov/cabinetoffice/gap/adminbackend/services/TechSupportUserService.java
> ran code formatter to fix build

- src/main/java/gov/cabinetoffice/gap/adminbackend/controllers/ApplicationFormSectionsController.java
- src/main/java/gov/cabinetoffice/gap/adminbackend/dtos/application/ApplicationSectionOrderPatchDto.java
- src/main/java/gov/cabinetoffice/gap/adminbackend/repositories/ApplicationFormRepository.java
- src/main/java/gov/cabinetoffice/gap/adminbackend/services/ApplicationFormSectionService.java
- src/test/java/gov/cabinetoffice/gap/adminbackend/controllers/ApplicationFormSectionsControllerTest.java
- src/test/java/gov/cabinetoffice/gap/adminbackend/services/ApplicationFormSectionServiceTest.java
Adds an endpoint and service method to change the order of sections when requested from the frontend
Ticket # and link [GAP-2102](https://technologyprogramme.atlassian.net/jira/software/projects/GAP/boards/216?selectedIssue=GAP-2102)
This can be merged independently of FE change.
Screenshots on FE PR
[GAP-2102]: https://technologyprogramme.atlassian.net/browse/GAP-2102?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> GAP-2102: Application section reordering

- src/main/java/gov/cabinetoffice/gap/adminbackend/dtos/user/CreateTechSupportUserDto.java
- src/main/java/gov/cabinetoffice/gap/adminbackend/services/TechSupportUserService.java
> Updates funding org query to create if none is found

- src/main/java/gov/cabinetoffice/gap/adminbackend/controllers/ApplicationFormSectionsController.java
- src/main/java/gov/cabinetoffice/gap/adminbackend/services/ApplicationFormSectionService.java
- src/test/java/gov/cabinetoffice/gap/adminbackend/controllers/ApplicationFormSectionsControllerTest.java
- src/test/java/gov/cabinetoffice/gap/adminbackend/services/ApplicationFormSectionServiceTest.java
Adds an endpoint which allows an admin to change a section title
Related pr: https://github.com/cabinetoffice/gap-find-apply-web/pull/279
> GAP-2103 - Edit section title

- src/main/java/gov/cabinetoffice/gap/adminbackend/constants/ValidationMaps.java
related pr: https://github.com/cabinetoffice/gap-find-apply-web/pull/288
> Bump default character limit 

- pom.xml
- src/main/java/gov/cabinetoffice/gap/adminbackend/controllers/ApplicationFormQuestionsController.java
- src/main/java/gov/cabinetoffice/gap/adminbackend/services/ApplicationFormService.java
- src/test/java/gov/cabinetoffice/gap/adminbackend/controllers/ApplicationFormQuestionsControllerTest.java
- src/test/java/gov/cabinetoffice/gap/adminbackend/services/ApplicationFormServiceTest.java
Ticket [GAP-2111](https://technologyprogramme.atlassian.net/jira/software/projects/GAP/boards/216?selectedIssue=GAP-2111)
- New endpoint for re-ordering questions within a section within an application form by a given increment
https://github.com/cabinetoffice/gap-find-admin-backend/assets/101722961/5241076e-f046-444d-ad62-36eb0dcabd81
[GAP-2111]: https://technologyprogramme.atlassian.net/browse/GAP-2111?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> GAP-2111: Question reordering

- src/main/java/gov/cabinetoffice/gap/adminbackend/services/GrantAdvertService.java
> replacing restTemplate with WebClientBuilder

- src/main/java/gov/cabinetoffice/gap/adminbackend/services/GrantAdvertService.java
- src/test/java/gov/cabinetoffice/gap/adminbackend/services/GrantAdvertServiceTest.java
> Makes web client final and fixes unit tests

- src/main/java/gov/cabinetoffice/gap/adminbackend/services/GrantAdvertService.java
> do not send multiple content-type headers

- src/main/java/gov/cabinetoffice/gap/adminbackend/services/ApplicationFormService.java
> GAP-2391: Validate max words field in post question endpoint

- src/main/java/gov/cabinetoffice/gap/adminbackend/enums/GrantExportStatus.java
- src/main/resources/db/migration/V1_91__create_grant_export_batch_table.sql
Add flyway migration to create the grant_export_batch table
https://technologyprogramme.atlassian.net/browse/TMI2-602
> TMI2-630 - Add grant_export_batch table

- src/main/resources/db/migration/V1_91__adjust_hint_text_section_one_funding_org.sql
GAP-2431: https://technologyprogramme.atlassian.net/browse/GAP-2431
> GAP-2431: Update hint text on ad builder for funding org question

- src/main/java/gov/cabinetoffice/gap/adminbackend/enums/GrantExportStatus.java
- src/main/java/gov/cabinetoffice/gap/adminbackend/services/SubmissionsService.java
- src/test/java/gov/cabinetoffice/gap/adminbackend/services/SubmissionsServiceTest.java
added FAILED to grant export enum
TMI2-630: https://technologyprogramme.atlassian.net/browse/TMI2-630
> TMI2-630 added FAILED to grant export enum

- src/main/resources/db/migration/V1_92__remove-word-from-ad-builder-org-hint-text.sql
FIX for [GAP-2431](https://technologyprogramme.atlassian.net/browse/GAP-2431)
[GAP-2431]: https://technologyprogramme.atlassian.net/browse/GAP-2431?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> Remove 'the' from copy.

- src/main/java/gov/cabinetoffice/gap/adminbackend/config/LambdasInterceptor.java
- src/main/java/gov/cabinetoffice/gap/adminbackend/controllers/GrantExportBatchController.java
- src/main/java/gov/cabinetoffice/gap/adminbackend/controllers/GrantExportController.java
- src/main/java/gov/cabinetoffice/gap/adminbackend/entities/GrantExportBatchEntity.java
- src/main/java/gov/cabinetoffice/gap/adminbackend/repositories/GrantExportBatchRepository.java
- src/main/java/gov/cabinetoffice/gap/adminbackend/services/GrantExportBatchService.java
- src/main/java/gov/cabinetoffice/gap/adminbackend/services/GrantExportService.java
- src/main/java/gov/cabinetoffice/gap/adminbackend/services/SubmissionsService.java
- src/test/java/gov/cabinetoffice/gap/adminbackend/controllers/GrantExportBatchControllerTest.java
- src/test/java/gov/cabinetoffice/gap/adminbackend/controllers/GrantExportControllerTest.java
- src/test/java/gov/cabinetoffice/gap/adminbackend/services/GrantExportBatchServiceTest.java
- src/test/java/gov/cabinetoffice/gap/adminbackend/services/GrantExportServiceTest.java
- src/test/java/gov/cabinetoffice/gap/adminbackend/services/SubmissionsServiceTest.java
Adds GrantExportBatchEntity, controller and service to handle creating grantExportBatch, updating its status and location for the submission export lambda
TMI2-631: https://technologyprogramme.atlassian.net/browse/TMI2-631
> TMI2-631: handle grant export batch

- src/main/resources/db/migration/V1_94__add_local_authority_enum_to_mandatory_question_org_type.sql
[TMI2-628 - Add local authority option for an applicant](https://technologyprogramme.atlassian.net/browse/TMI2-628)
> TMI2-628 - Add local authority to applicant organisation and MQs

- src/main/java/gov/cabinetoffice/gap/adminbackend/enums/GrantMandatoryQuestionOrgType.java
> TMI2-628 - Adds missing enum

- src/main/java/gov/cabinetoffice/gap/adminbackend/controllers/GrantExportController.java
- src/main/java/gov/cabinetoffice/gap/adminbackend/dtos/FailedExportCountDTO.java
- src/main/java/gov/cabinetoffice/gap/adminbackend/repositories/GrantExportRepository.java
- src/main/java/gov/cabinetoffice/gap/adminbackend/services/GrantExportService.java
- src/test/java/gov/cabinetoffice/gap/adminbackend/controllers/GrantExportControllerTest.java
- src/test/java/gov/cabinetoffice/gap/adminbackend/services/GrantExportServiceTest.java
added endpoint to be used by submission export lambda to get failed export count
TMI2-606: 
https://technologyprogramme.atlassian.net/browse/TMI2-606
> TMI2-606: SNS support email

- .github/workflows/feature.yml
- src/main/java/gov/cabinetoffice/gap/adminbackend/entities/GrantAdmin.java
- src/main/java/gov/cabinetoffice/gap/adminbackend/entities/SchemeEntity.java
- src/main/java/gov/cabinetoffice/gap/adminbackend/security/AuthManager.java
- src/main/java/gov/cabinetoffice/gap/adminbackend/services/SchemeService.java
- src/main/resources/db/migration/V1_95__add_new_scheme_editors_table.sql
- src/test/java/gov/cabinetoffice/gap/adminbackend/services/FeedbackServiceTest.java
- src/test/java/gov/cabinetoffice/gap/adminbackend/services/GrantAdvertServiceTest.java
- src/test/java/gov/cabinetoffice/gap/adminbackend/services/SchemeServiceTest.java
- src/test/java/gov/cabinetoffice/gap/adminbackend/testdata/LoginTestData.java
- src/test/java/gov/cabinetoffice/gap/adminbackend/testdata/SchemeTestData.java
- src/test/java/gov/cabinetoffice/gap/adminbackend/testdata/generators/RandomGrantAdvertGenerators.java
Merging the co-auth feature branch into develop as it is no longer required.
> Merging Co-auth feature branch into develop

- src/main/java/gov/cabinetoffice/gap/adminbackend/repositories/ApplicationFormRepository.java
- src/main/java/gov/cabinetoffice/gap/adminbackend/services/ApplicationFormService.java
- src/test/java/gov/cabinetoffice/gap/adminbackend/services/ApplicationFormServiceTest.java
> Adds query to find application with no ownership check

- src/main/java/gov/cabinetoffice/gap/adminbackend/dtos/user/DecryptedUserEmailResponse.java
- src/main/java/gov/cabinetoffice/gap/adminbackend/services/SchemeEditorService.java
- src/test/java/gov/cabinetoffice/gap/adminbackend/services/SchemeEditorServiceTest.java
Matches an editors email address using their sub (instead of matching with the index on the initial user-subs array)
> Fix editor email mapping

- src/main/java/gov/cabinetoffice/gap/adminbackend/repositories/SchemeRepository.java
- src/main/java/gov/cabinetoffice/gap/adminbackend/services/SchemeEditorService.java
- src/test/java/gov/cabinetoffice/gap/adminbackend/services/SchemeEditorServiceTest.java
Use createdBy field during isOwner check within SchemeEditorsService
> Use createdBy during isOwner check

- src/main/java/gov/cabinetoffice/gap/adminbackend/entities/GrantExportEntity.java
- src/main/java/gov/cabinetoffice/gap/adminbackend/services/SubmissionsService.java
- src/test/java/gov/cabinetoffice/gap/adminbackend/services/SubmissionsServiceTest.java
https://technologyprogramme.atlassian.net/browse/TMI2-602
Add schemeID to submission export SQS message to support sending admin email in all cases
> TMI2-602: Add schemeId to submission export SQS message

- src/main/java/gov/cabinetoffice/gap/adminbackend/entities/GrantExportEntity.java
> TMI2-602: ignore schemeId field in JPA for GrantExportEntity

- src/main/java/gov/cabinetoffice/gap/adminbackend/dtos/grantadvert/GetGrantAdvertPublishingInformationResponseDTO.java
- src/main/java/gov/cabinetoffice/gap/adminbackend/entities/GrantAdvert.java
- src/main/java/gov/cabinetoffice/gap/adminbackend/services/GrantAdvertService.java
- src/main/resources/db/migration/V1_96__add_valid_last_updated.sql
- src/test/java/gov/cabinetoffice/gap/adminbackend/controllers/GrantAdvertControllerTest.java
additional ac added against this ticket https://technologyprogramme.atlassian.net/jira/software/projects/GAP/boards/216?selectedIssue=GAP-2432
Related pr: https://github.com/cabinetoffice/gap-find-apply-web/pull/367
> add validLastUpdated field

- src/main/java/gov/cabinetoffice/gap/adminbackend/controllers/ApplicationFormController.java
- src/main/java/gov/cabinetoffice/gap/adminbackend/repositories/ApplicationFormRepository.java
- src/main/java/gov/cabinetoffice/gap/adminbackend/services/ApplicationFormSectionService.java
- src/main/java/gov/cabinetoffice/gap/adminbackend/services/ApplicationFormService.java
- src/test/java/gov/cabinetoffice/gap/adminbackend/controllers/ApplicationFormControllerTest.java
- src/test/java/gov/cabinetoffice/gap/adminbackend/services/ApplicationFormServiceTest.java
Adds an endpoint which allows us to get the email address of the "Last Updated By" admin ID field on an application.
Ticket # and link [GAP-2433](https://technologyprogramme.atlassian.net/jira/software/projects/GAP/boards/216?selectedIssue=GAP-2433)
New endpoint.
New service methods to support endpoint functionality
[GAP-2433]: https://technologyprogramme.atlassian.net/browse/GAP-2433?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> GAP-2433: View last updated by (Applications)

- src/main/java/gov/cabinetoffice/gap/adminbackend/controllers/ApplicationFormController.java
- src/main/java/gov/cabinetoffice/gap/adminbackend/controllers/UserController.java
- src/main/java/gov/cabinetoffice/gap/adminbackend/listeners/SchemeUpdateListener.java
- src/main/java/gov/cabinetoffice/gap/adminbackend/services/ApplicationFormService.java
- src/main/java/gov/cabinetoffice/gap/adminbackend/services/GrantAdvertService.java
- src/main/java/gov/cabinetoffice/gap/adminbackend/services/SchemeService.java
- src/main/java/gov/cabinetoffice/gap/adminbackend/services/UserService.java
- src/main/resources/db/migration/V1_97__alter_lastupdatedby_and_createdby_null_constraints.sql
- src/test/java/gov/cabinetoffice/gap/adminbackend/controllers/ApplicationFormControllerTest.java
- src/test/java/gov/cabinetoffice/gap/adminbackend/controllers/UserControllerTest.java
- src/test/java/gov/cabinetoffice/gap/adminbackend/services/ApplicationFormServiceTest.java
- src/test/java/gov/cabinetoffice/gap/adminbackend/services/GrantAdvertServiceTest.java
- src/test/java/gov/cabinetoffice/gap/adminbackend/services/SchemeServiceTest.java
> Adds functionality to remove admin reference when deleted

- src/main/java/gov/cabinetoffice/gap/adminbackend/controllers/ApplicationFormQuestionsController.java
- src/main/java/gov/cabinetoffice/gap/adminbackend/services/ApplicationFormService.java
- src/test/java/gov/cabinetoffice/gap/adminbackend/controllers/ApplicationFormQuestionsControllerTest.java
- src/test/java/gov/cabinetoffice/gap/adminbackend/services/ApplicationFormServiceTest.java
[GAP-2461](https://technologyprogramme.atlassian.net/browse/GAP-2461)
Multiple editor delete question
https://github.com/cabinetoffice/gap-find-apply-web/pull/387
[GAP-2461]: https://technologyprogramme.atlassian.net/browse/GAP-2461?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> GAP-2461: Multiple Editors - delete question

- src/main/java/gov/cabinetoffice/gap/adminbackend/controllers/SchemeController.java
- src/main/java/gov/cabinetoffice/gap/adminbackend/services/ApplicationFormService.java
- src/main/java/gov/cabinetoffice/gap/adminbackend/services/GrantAdvertService.java
- src/main/java/gov/cabinetoffice/gap/adminbackend/services/SchemeService.java
- src/test/java/gov/cabinetoffice/gap/adminbackend/controllers/SchemeControllerTest.java
- src/test/java/gov/cabinetoffice/gap/adminbackend/services/ApplicationFormServiceTest.java
- src/test/java/gov/cabinetoffice/gap/adminbackend/services/GrantAdvertServiceTest.java
- src/test/java/gov/cabinetoffice/gap/adminbackend/services/SchemeServiceTest.java
- Owners are now added to/removed from the `scheme_editors` table as part of an ownership change.
- If a new owner is an existing editor then they are not added again
- general refactoring and sonar suggestions
[Ticket link](https://technologyprogramme.atlassian.net/jira/software/projects/GAP/boards/216?selectedIssue=GAP-2439)
- see above
> GAP-2439: Fixing the change of ownership functionality

- src/main/java/gov/cabinetoffice/gap/adminbackend/controllers/ApplicationFormQuestionsController.java
- src/main/java/gov/cabinetoffice/gap/adminbackend/services/ApplicationFormService.java
- src/test/java/gov/cabinetoffice/gap/adminbackend/controllers/ApplicationFormQuestionsControllerTest.java
- src/test/java/gov/cabinetoffice/gap/adminbackend/services/ApplicationFormServiceTest.java
[GAP-2463](https://technologyprogramme.atlassian.net/browse/GAP-2463)
https://github.com/cabinetoffice/gap-find-apply-web/pull/391
[GAP-2463]: https://technologyprogramme.atlassian.net/browse/GAP-2463?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> GAP-2463: Multiple Editors question reorder

- src/main/java/gov/cabinetoffice/gap/adminbackend/mappers/SchemeMapper.java
> Fixes lastUpdatedBy on scheme level when a user is deleted

- src/main/java/gov/cabinetoffice/gap/adminbackend/controllers/UserController.java
- src/main/java/gov/cabinetoffice/gap/adminbackend/security/WebSecurityConfig.java
- src/main/java/gov/cabinetoffice/gap/adminbackend/services/GrantAdvertService.java
- src/main/java/gov/cabinetoffice/gap/adminbackend/services/SchemeService.java
- src/main/java/gov/cabinetoffice/gap/adminbackend/services/UserService.java
- src/test/java/gov/cabinetoffice/gap/adminbackend/controllers/UserControllerTest.java
- src/test/java/gov/cabinetoffice/gap/adminbackend/services/UserServiceTest.java
> handles removing admin reference

- src/main/java/gov/cabinetoffice/gap/adminbackend/controllers/GrantAdvertController.java
- src/main/java/gov/cabinetoffice/gap/adminbackend/dtos/grantadvert/CreateGrantAdvertDto.java
- src/main/java/gov/cabinetoffice/gap/adminbackend/dtos/schemes/SchemePostDTO.java
- src/test/java/gov/cabinetoffice/gap/adminbackend/controllers/GrantAdvertControllerTest.java
- src/test/java/gov/cabinetoffice/gap/adminbackend/controllers/SessionsControllerTest.java
- src/test/java/gov/cabinetoffice/gap/adminbackend/testdata/SchemeTestData.java
- src/test/java/gov/cabinetoffice/gap/adminbackend/testdata/SessionTestData.java
> amend scheme and advert name fields

- src/main/java/gov/cabinetoffice/gap/adminbackend/mappers/SchemeMapper.java
> fix grant name mapping

- src/main/java/gov/cabinetoffice/gap/adminbackend/services/ApplicationFormService.java
utilising a method to check for anonymous sessions to prevent exceptions. 
[GAP-2510](https://technologyprogramme.atlassian.net/jira/software/projects/GAP/boards/216?selectedIssue=GAP-2510)
see above
[GAP-2510]: https://technologyprogramme.atlassian.net/browse/GAP-2510?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> GAP-2510: helper method to check for anonymous sessions

- src/main/java/gov/cabinetoffice/gap/adminbackend/services/GrantAdvertService.java
- src/test/java/gov/cabinetoffice/gap/adminbackend/services/GrantAdvertServiceTest.java
- Optionally publishing/unpublishing based on the ads state within contentful
- Asynchronously publishing/updating elastic search
> GAP-2509: Defend against timeout when publishing

- src/main/java/gov/cabinetoffice/gap/adminbackend/client/UserServiceClient.java
- src/main/java/gov/cabinetoffice/gap/adminbackend/config/UserServiceConfig.java
- src/main/java/gov/cabinetoffice/gap/adminbackend/services/UserService.java
- src/main/java/gov/cabinetoffice/gap/adminbackend/utils/HelperUtils.java
- src/main/resources/application.properties
- src/main/resources/db/migration/V1_76__adding_event-service_tables.sql
- src/test/java/gov/cabinetoffice/gap/adminbackend/client/UserServiceClientTest.java
> Tmi2 555/encrypt secret on internal user service requests

- src/main/java/gov/cabinetoffice/gap/adminbackend/dtos/grantadvert/GetGrantAdvertPublishingInformationResponseDTO.java
- src/main/java/gov/cabinetoffice/gap/adminbackend/entities/GrantAdvert.java
- src/main/java/gov/cabinetoffice/gap/adminbackend/services/GrantAdvertService.java
- src/test/java/gov/cabinetoffice/gap/adminbackend/controllers/GrantAdvertControllerTest.java
- src/test/java/gov/cabinetoffice/gap/adminbackend/services/GrantAdvertServiceTest.java
> adjust for BST when setting grant opening/closing dates

- src/main/java/gov/cabinetoffice/gap/adminbackend/services/OpenSearchService.java
Improves logging around updating and deleting open search for debugging purposes
> Improves logs around updating and deleting open search

- src/main/java/gov/cabinetoffice/gap/adminbackend/services/OpenSearchService.java
> Improves logs around updating and deleting open search (#280)

- src/main/java/gov/cabinetoffice/gap/adminbackend/exceptions/IndexingException.java
- src/main/java/gov/cabinetoffice/gap/adminbackend/services/GrantAdvertService.java
- src/main/java/gov/cabinetoffice/gap/adminbackend/services/OpenSearchService.java
- src/test/java/gov/cabinetoffice/gap/adminbackend/services/OpenSearchServiceTest.java
> Release 10.2: Improving open search logging

- src/main/java/gov/cabinetoffice/gap/adminbackend/services/UserService.java
- src/test/java/gov/cabinetoffice/gap/adminbackend/services/UserServiceTest.java
GAP-2523: https://technologyprogramme.atlassian.net/browse/GAP-2523
Clean up logic to make call to user service regardless of role to fix issue where user with **only SUPER ADMIN role** couldn't have a grant transferred to them.
> GAP-2523: Super admin only grant ownership

- src/main/java/gov/cabinetoffice/gap/adminbackend/services/GrantAdvertService.java
- src/test/java/gov/cabinetoffice/gap/adminbackend/services/GrantAdvertServiceTest.java
> Fixing (or partially fixing) issues with sending grants to open search

- src/main/java/gov/cabinetoffice/gap/adminbackend/config/WebClientConfig.java
> trying to force web client to use new connections

- src/main/java/gov/cabinetoffice/gap/adminbackend/config/WebClientConfig.java
> re-adding the web client config

- src/main/java/gov/cabinetoffice/gap/adminbackend/controllers/UserController.java
https://technologyprogramme.atlassian.net/browse/GAP-2619
> convert admin email to lowercase before validation

- src/main/java/gov/cabinetoffice/gap/adminbackend/validation/validators/AdvertPageResponseValidator.java
- src/test/java/gov/cabinetoffice/gap/adminbackend/validation/validators/AdvertPageResponseValidatorTest.java
> url validation updated to accept # symbol

- src/main/java/gov/cabinetoffice/gap/adminbackend/controllers/SchemeEditorController.java
> existing unknown change removed

- pom.xml
See https://technologyprogramme.atlassian.net/browse/LSS-550
> LSS-550 Update Apache Commons IO to version 2.19.0
